"""empty message

Revision ID: 62152c339791
Revises: 09df58349459
Create Date: 2019-10-31 17:12:10.596344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62152c339791'
down_revision = '09df58349459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
